language: julia

os:
  - linux
  - osx

julia:
  - nightly
  - 1.0.0
  - 0.7.0

matrix:
  allow_failures:
    - julia: nightly

after-success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'